version: "3.8"

services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/config/nginx/ssl/server-key.pem:/etc/nginx/ssl/server-key.pem
      - ./docker/config/nginx/ssl/server.pem:/etc/nginx/ssl/server.pem
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    networks:
      - cadastro_vendas_network

  php:
    image: thiagotrancoso/php7.4-fpm-dev:v3
    container_name: php
    volumes:
      - ./:/var/www
      - ./docker/config/php/conf.d:/usr/local/etc/php/conf.d
    working_dir: /var/www
    depends_on:
      - postgres
    networks:
      - cadastro_vendas_network

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: cadastro_vendas
      POSTGRES_PASSWORD: postgres
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cadastro_vendas_network

volumes:
  volume_postgres:

networks:
  cadastro_vendas_network:
    driver: bridge
